In [2]:
import numpy as np
names = np.array(['juan','carlos','carlos','juan','pepe','pepe','pepe'])
compras = np.array([500,100,300,400,1000,50,500])


2850

In [12]:
names

array(['juan', 'carlos', 'carlos', 'juan', 'pepe', 'pepe', 'pepe'],
      dtype='<U6')

In [13]:
compras

array([ 500,  100,  300,  400, 1000,   50,  500])

In [14]:
compras.sum()

2850

In [15]:
compras[names == 'juan']

array([500, 400])

In [16]:
compras[names == 'juan'].sum()

900

In [17]:
compras[names == 'pepe']

array([1000,   50,  500])

In [9]:
compras[names == 'pepe'].sum()

1550

In [19]:
compras[names == 'carlos']

array([100, 300])

In [31]:
compras[(names == 'juan') | (names == 'carlos')].sum()

1300