In [6]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [7]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 15.3 ms, sys: 5.35 ms, total: 20.7 ms
Wall time: 18.9 ms


In [8]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: user 705 ms, sys: 140 ms, total: 846 ms
Wall time: 845 ms


In [11]:
np.random.uniform(low=0.5, high=13.3, size=
                  (3,3))

array([[10.8452359 ,  7.251807  ,  6.56745897],
       [12.86312271, 13.23343031,  6.22532014],
       [ 5.65630031,  8.15904694,  7.85689036]])

In [14]:
data = np.random.randn(2,3)
data

array([[ 0.61790761,  0.38845581, -1.42598308],
       [-0.5064647 , -1.27869651,  0.44893751]])

In [16]:
data * 10

array([[  6.17907606,   3.88455812, -14.25983082],
       [ -5.06464703, -12.78696505,   4.48937506]])

In [17]:
data + data

array([[ 1.23581521,  0.77691162, -2.85196616],
       [-1.01292941, -2.55739301,  0.89787501]])

In [18]:
data.shape

(2, 3)

In [20]:
data.dtype

dtype('float64')

In [21]:
data1=[6,6.75,8,0,1]
arr1 = np.array(data1)
arr1

array([6.  , 6.75, 8.  , 0.  , 1.  ])

In [26]:
data2 = [[1,2,3,4],[5,6,7,8,]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr2.shape

(2, 4)

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
np.empty((2,3,2))

array([[[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000, -3.11108209e+231],
        [ 2.68156159e+154, -1.49457262e-154]]])

In [35]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
arr3 = np.array([1.0,2,3],dtype=np.int32)
arr3

array([1, 2, 3], dtype=int32)

In [45]:
arr3.dtype

dtype('int32')

In [46]:
arr4 = np.array([1,2,3,4,5])

In [57]:
arr4.dtype

dtype('int64')

In [48]:
float_arr = arr4.astype(np.float64)

In [51]:
float_arr.dtype

dtype('float64')

In [58]:
arr5 = np.array(['a','b','c'])
arr5

array(['a', 'b', 'c'], dtype='<U1')

In [59]:
arr5.dtype

dtype('<U1')

In [68]:
arr6 = np.array([[1,2,3],[4.,5.,6.]])
arr6

array([[1., 2., 3.],
       [4., 5., 6.]])

In [69]:
1 / arr6

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [70]:
arr6 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [71]:
arr7 = np.array([[0,4,1],[7,2,12]])
arr8 = np.array([[1,2,3],[4,5,6]])
arr7 > 8


array([[False, False, False],
       [False, False,  True]])

In [72]:
arr6.dtype

dtype('float64')

In [73]:
arr9 = np.arange(10)
arr9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr10 = arr9[5:8]
arr10

array([5, 6, 7])

In [78]:
arr9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr11 = arr9[5:8].copy()
arr11

array([5, 6, 7])

In [92]:
arr12 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
arr12

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])